### ISSUE TITLE
Set :focus for Form Elements Sighted 

### ISSUE THREAD

**Issue by DarekRepos** [DarekRepos/FAQ-accordion#8]
keyboard users rely on focus to determine where keyboard events go in the page. Make focus for form elements stand out and consistent than a browser's default implementation:  
```css
//example
 a:focus,
 button:focus,
 input:focus,
 select:focus,
 textarea:focus { 
   box-shadow: none; 
   outline: #000 dotted 2px;   
   outline-offset: .05em; 
}
```
